# Generated by Django 2.0.1 on 2018-03-17 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
