# Generated by Django 2.0.1 on 2018-03-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0002_auto_20180317_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loginapp.UserProfileInfo'),
        ),
    ]
