# Generated by Django 2.0.1 on 2018-03-17 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0003_auto_20180317_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collegename', to='Loginapp.College'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatorname', to='Loginapp.UserProfileInfo'),
        ),
    ]
