# Generated by Django 2.0.1 on 2018-03-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0004_auto_20180317_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='creator',
        ),
    ]
