# Generated by Django 2.0.1 on 2018-03-17 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0005_remove_problem_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collegename', to='Loginapp.College'),
        ),
    ]
