# Generated by Django 2.0.2 on 2018-03-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0006_auto_20180317_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='booltrue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
