# Generated by Django 2.0.1 on 2018-03-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0007_auto_20180318_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
