# Generated by Django 2.0 on 2018-04-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0008_auto_20180318_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='rating_dislikes',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='rating_likes',
        ),
    ]
