# Generated by Django 2.0.1 on 2018-03-16 20:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='doc_image',
            field=models.ImageField(default='profile_pics/sumit.jpg', upload_to='documents'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='first_name',
            field=models.CharField(default='firstname', max_length=60),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='last_name',
            field=models.CharField(default='lastname', max_length=60),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='mob_no',
            field=models.CharField(default='67567574', max_length=13),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='college',
            field=models.ForeignKey(default='Coll', on_delete=django.db.models.deletion.CASCADE, to='Loginapp.College'),
        ),
    ]
