# Generated by Django 2.0.1 on 2018-03-16 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Loginapp', '0002_auto_20180317_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loginapp.College'),
        ),
    ]
